// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5TIMdBWQthSDFBYHCxj2jOpInOkHLOEo',
    appId: '1:906549778834:android:97845ffb3cb1121421894b',
    messagingSenderId: '906549778834',
    projectId: 'pinksnap-mobile-app',
    authDomain: 'pinksnap-mobile-app.firebaseapp.com',
    storageBucket: 'pinksnap-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5TIMdBWQthSDFBYHCxj2jOpInOkHLOEo',
    appId: '1:906549778834:android:97845ffb3cb1121421894b',
    messagingSenderId: '906549778834',
    projectId: 'pinksnap-mobile-app',
    storageBucket: 'pinksnap-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5TIMdBWQthSDFBYHCxj2jOpInOkHLOEo',
    appId: '1:906549778834:android:97845ffb3cb1121421894b',
    messagingSenderId: '906549778834',
    projectId: 'pinksnap-mobile-app',
    storageBucket: 'pinksnap-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.pinksmapmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5TIMdBWQthSDFBYHCxj2jOpInOkHLOEo',
    appId: '1:906549778834:android:97845ffb3cb1121421894b',
    messagingSenderId: '906549778834',
    projectId: 'pinksnap-mobile-app',
    storageBucket: 'pinksnap-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.pinksmapmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5TIMdBWQthSDFBYHCxj2jOpInOkHLOEo',
    appId: '1:906549778834:android:97845ffb3cb1121421894b',
    messagingSenderId: '906549778834',
    projectId: 'pinksnap-mobile-app',
    authDomain: 'pinksnap-mobile-app.firebaseapp.com',
    storageBucket: 'pinksnap-mobile-app.firebasestorage.app',
  );
}
